### ISSUE TITLE
Is colour-value an obsv property?

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-domain#10]
relates to #4 
we have colour-value as an obsv property. Is colour-value an obsv property @dr-shorthair  or a value space that the obsv prop colour can be described by?
We don't have an observable property of colour by the way.

**Comment by meganrwong** [comment]
sprop:colour-stat 
'moisture status for colour description' 
would this go under observable property of 'moisture' and 'colour' @dr-shorthair ?

**Comment by meganrwong** [comment]
So, if you got result of colour that did not follow the text under the 'colour' header in the yellow book "using the Munsell Colour System", can people still map their data against the obsv prop "colour" ?

We had this problem in VAS applying the yellow book - texture and colour are the two examples I can think of. Because the observable properties are tied up with a description of the YB method sometimes. The observable properties are not always discreetly defined through YB text.

**Comment by dr-shorthair** [comment]
'Typically using the Munsell Colour System' should be a usage note rather than essential part of the definition.

**Comment by meganrwong** [comment]
so this obsv property is 'colour' rather than colour-value as we have?

would that usage note go with 'colour' or over with the colour-value collection? 

over in #4 which was similar, I put the yb text under field-texture in as note under field-texture. Used skos:note

**Comment by meganrwong** [comment]
actually I think we need obsv prop 'colour' and 'soil-colour' 
because we also have mottle-colour to put in under colour. 
I'd put the def of colour from yb (ie saying it is measured by munsell) as a note under soil-colour 

And colour-value will be the value-space

**Comment by dr-shorthair** [comment]
Yes, it should be `colour` not `colour value`. 
I was reproducing the structure in the YB where the moisture state is recorded alongside the value, but that is more like part of the observation procedure or metadata.

**Comment by meganrwong** [comment]
sprop:colour>sprop:soil-colour
sprop:colour>sprop:mottle-colour
skos:related:colour-stat
