### ISSUE TITLE
create higher level obsv prop - ASLS

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-domain#2]
Added for soil profile chapter, with members -  

**DEPTH**  

**TYPE** 

ABUNDANCE  Has some hierarchy within. Voids-macropores-abundance-course and –fine – I put under voids-macropores-abundance 

**SIZE** - this went at top level as is not re geographical or linear extent necessarily

**DISTINCTNESS** 
 
**STRENGTH** – already created - Checked has all 5 members (2 parents, 3 child) 

**LITHOLOG**Y – already created  - Checked has all members 

 **SHAPE** 

**GRADE**

 **QUALIFICATION**

**Comment by meganrwong** [comment]
QUESTION - from soil profile chapter ASLS

STRUCTURE  

added - Structure-articifial-aggregates, Pans-structure , Material-structure 

The following instances seemed to have  two high level properties - 

sprop:structure-pedality-grade - skos:narrower : GRADE, STRUCTURE  

sprop:structure-pedality-size - skos:narrower : SIZE, STRUCTURE 

sprop:structure-pedality-type - skos:narrower : TYPE,  STRUCTURE 

grade, size and type are not exclusive to structure 

Is there a better way of doing than this? - 

![image](https://user-images.githubusercontent.com/49380601/183564982-10754a2b-2658-40ab-ae6f-d44b6c2937a8.png)

**Comment by meganrwong** [comment]
just for the record, think this is ok - 

GRADE – 
There is field-soil-texture-mineral  'grade' was not in the URI but it was in the prefLabel:Mineral soils field texture grade. 

So, I to ‘grade’

field-soil-texture-organic is not a grade - so not added under 'grad

**Comment by meganrwong** [comment]
QUESTION 

QUALIFICATION – added  

Member - ‘field-texture-qualification' 

not sure it is an obsv prop  

It may have a relationship to GRADE and its member field-texture-grade that may need to be expressed, but I’m not sure that is in scope of what we are doing here atm (may be skos:related of ‘field-texture-qualification' and ‘field-texture-grade')

**Comment by meganrwong** [comment]
QUESTION

CONSISTENCE – Not created as high level obsv prop - reasonable not to?

I’m not sure consistence should be split out – perhaps the following just go under ‘strength’ ‘type’ and ‘degree’ 

sprop:consistence-strength 

sprop:consistence-plasticity-type 

sprop:consistence-plasticity-degree

**Comment by meganrwong** [comment]
for record here is what has not been added as Observable Properties from ASLS soil profile chapter as there was only one instance. Could be added later as/if required. Let me know if you want any added now. 

Have not add these higher level obsv prop – they have only 1 instance under 

PERMEABILITY 

DRAINAGE

MAGNETIC-**ATTRIBUTES** 

EFFERVESCENCE of carbonates in fine earth 

CEMENTATION

CONTINUITY  

NATURE 

FORM 

CONDITION 

FABRIC 

DIAMETER - would go under linear extent 

CONTRAST 

 

?COLOUR – does not make sense to create given contexts is it found in (3 instances all with different use of colour) 

Mottle-colour, colour-value and colour-stat 

 

?DISTRIBUTION – only 1 instance 

Course-fragment-distribution 

 

 

(FIELD – not obsv prop) - does not make sense to add as upper level P161 – Field texture

**Comment by meganrwong** [comment]
@dr-shorthair Are we missing Obsv Prop members - under 'Fabric'  - earthy, sandy rough and smooth?  p181

**Comment by meganrwong** [comment]
here are some additional notes when pulling higher level obsv prop from soil profile chapter. Apologies putting them all here, just so they don't get lost for now - 


Is horizon name prefix and horizon name suffix an obsv prop? They are not  in Obsv Prop collection 

Are we only putting coded in? are transitional horizons, bleached horizons and cracking clays features 

I can’t tell where subdivisions of horizons, lithological discontinuities and buried soils fit in SOSA model. They are more instructive re how to assign horizon classifiers?

sprop:depth def: Give depth to the entity at the site of soil observation, in metres, either above or below the soil surface, excluding litter and living vegetation  - source of defs? 

What obsv prop would colours be recorded against that are not recorded as hue, value chroma (e.g. ‘brown’ ‘yellowish brown’ ‘brown yellow’) 

P160.  I think that all these obsv prop eg abundance, size, relate to types M, X, Y, Z – not just to mottles? – so mottle may be an obsv property rather than a feature? 

Texture 

Sprop:texture – should this be field texture? (outside of this there are lab-texture and texture) 

(just noting there are lots of rules throughout not yet encoded – eg ‘if a soil is organic it must be qualified thus….’ P167) 

Can we accom field textures outside of YB classifiers, or when method is not known (do they all follow northcote – how can we tell particularly if they provide results outside of the YB classifiers?) 

Structure 

Are we missing sprop:structure-compound-pedality? Or is this a feature? P 180 

Where do clods and fragments go – are they features? Or obsv prop? P 181 

Fabric 

What are earthy, sandy, rough and smooth? Classifiers? 

Voids 

Creation of higher level obsv property is not always required/appropaite here is an example -  

(VOIDS>CRACKS) 

sprop:voids-cracks 

Voids and cracks also read as a feature type, hopefully people won’t misuse.....

**Comment by dr-shorthair** [comment]
In order to keep the issue-threads together, it is best to create a new issue for each question. 
I've copied your questions into new issues, as listed above, except for the last comment https://github.com/ANZSoilData/def-au-domain/issues/2#issuecomment-1208912454

**Comment by dr-shorthair** [comment]
> Is horizon name prefix and horizon name suffix an obsv prop? They are not in Obsv Prop collection
>
> Are we only putting coded in? are transitional horizons, bleached horizons and cracking clays features
>
> Are we only putting coded in? are transitional horizons, bleached horizons and cracking clays features

prefix, suffix etc are not observable properties. They are part of the coding scheme for the Horizon Classification. 

However, what _is_ missing is `sprop:horizon-classification a sosa:ObservableProperty .` whose value would be A2e, B2c, 2B2b, etc.

**Comment by meganrwong** [comment]
> > Is horizon name prefix and horizon name suffix an obsv prop? They are not in Obsv Prop collection
> > Are we only putting coded in? are transitional horizons, bleached horizons and cracking clays features
> > Are we only putting coded in? are transitional horizons, bleached horizons and cracking clays features
> 
> prefix, suffix etc are not observable properties. They are part of the coding scheme for the Horizon Classification.
> 
> However, what _is_ missing is `sprop:horizon-classification a sosa:ObservableProperty .` whose value would be A2e, B2c, 2B2b, etc.

Yep, good. created https://anzsoil.org/def/au/property/horizon-classification

Re the text def for that - I started getting text from YB from 'as horizon notation is deduced from the profile description......' but do we want this here? It is kind of 'how to' method stuff. As a general comment, the YB does not tend to have super clear defs for obsv properites......I"ve not been putting them in yet. for now, just have skos:def 'Horizon Classification'

**Comment by meganrwong** [comment]
@dr-shorthair so everything in upper case here we'd add these as observable properties even though they have only 1 member in Yellow book?

PERMEABILITY

DRAINAGE

MAGNETIC-ATTRIBUTES

EFFERVESCENCE (of carbonates in fine earth)

CEMENTATION

CONTINUITY

NATURE

FORM

CONDITION

FABRIC

DIAMETER - would go under linear extent

CONTRAST

DISTRIBUTION

**Comment by meganrwong** [comment]
has all been broken out to separate issues

**Comment by dr-shorthair** [comment]
Yes I think so
