### ISSUE TITLE
Site to SoilSite

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-domain#29]
original discussion paper was focused on Site
My changes reflect the feedback that this should be soil site discussion that this should be 'Soil Site'. 

For checking @dr-shorthair

**Comment by meganrwong** [comment]
I took out discussion of TERN plots (since there was no ref or anything to what a TERN plot was. 

What do you think the relationship btw Soil Site and TERN Site is @dr-shorthair 

https://w3id.org/tern/ontologies/tern/Site 

TERN site seems scoped to Ausplots Rangelands Sites - TERN site would be a type of Soil Site, but not sure how it would be best expressed......

**Comment by dr-shorthair** [comment]
I inserted `Land Survey Site` as a super-class. Using the name from the title of ASLS, to provide a hook for other non-soil-site specializations, or non-soil sites that are associated with soil investigations.

**Comment by dr-shorthair** [comment]
See https://github.com/ANZSoilData/def-au-domain/blob/main/site.md
