### ISSUE TITLE
Super-properties of structure properties

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-domain#3]
in https://github.com/ANZSoilData/def-au-domain/issues/2#issuecomment-1208901620 @meganrwong asked: 

QUESTION - from soil profile chapter ASLS

STRUCTURE

added - Structure-articifial-aggregates, Pans-structure , Material-structure

The following instances seemed to have two high level properties -

sprop:structure-pedality-grade - skos:narrower : GRADE, STRUCTURE

sprop:structure-pedality-size - skos:narrower : SIZE, STRUCTURE

sprop:structure-pedality-type - skos:narrower : TYPE, STRUCTURE

grade, size and type are not exclusive to structure

Is there a better way of doing these @dr-shorthair ?

![image](https://user-images.githubusercontent.com/49380601/183564982-10754a2b-2658-40ab-ae6f-d44b6c2937a8.png)

**Comment by dr-shorthair** [comment]
No problem with multiple super-properties. 
Remember: this is set-theory, not inheritance hierarchy. 
Ask the question: is every member of `sprop:structure-pedality-grade` also both a `GRADE` _and a_ `STRUCTURE`? 
If yes, then two parents is fine.

**Comment by meganrwong** [comment]
cool, thanks for clarifying
