### ISSUE TITLE
review GLOSIS observable properties for re-use

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-domain#31]
From S.Cox  -

1. take a local cache of the GLOSIS ontology repository - https://github.com/rapw3k/glosis.git 
2. Add the folder to you TopBraid Project (drag it into the Project Explorer)
3. Open `glosis_layer_horizon.ttl`
4. Run this SPARQL: 
```
SELECT * 
WHERE {
    ?o rdfs:subClassOf* glosis_lh:PhysioChemical ; rdfs:subClassOf ?os .
    ?os a owl:Restriction ; owl:onProperty sosa:observedProperty ; owl:hasValue ?op .
}
```
First you have to understand that the observed-properties of the sub-classes are fixed in `owl:Restriction` subclasses. 
The query `WHERE` clause works as follows: 
- find each sub-class (any depth) `?o` of `glosis_lh:PhysioChemical`, and load its sub-class URIs into the variable `?os` 
- test each `?os` to see if it matches the pattern (i.e. filter) that it is (i) an `owl:Restriction` (ii) on the property `sosa:observedProperty`, and (iii) load the value of its `owl:hasValue` into the variable ?op

The query `SELECT` clause reports all the variables that satisfy these patterns.  

However, I also see a lot of ObservableProperties in GLOSIS - 
- in `glosis_layer_horizon.ttl` e.g. `http://w3id.org/glosis/model/layerhorizon#coatingAbundanceProperty`  `http://w3id.org/glosis/model/layerhorizon#carbonInorganicProperty`
- in `glosis_common.ttl` e.g. `http://w3id.org/glosis/model/common#rockAbundanceProperty`
- and `glosis_cl.ttl` appears to be all the codelists

_Originally posted by @dr-shorthair in https://github.com/ANZSoilData/def-au-domain/issues/30#issuecomment-1278279261_

**Comment by dr-shorthair** [comment]
See https://github.com/ANZSoilData/def-au-domain/blob/main/GLOSIS-physiochemical-properties.txt

**Comment by dr-shorthair** [comment]
[GLOSIS-physiochemical-properties.txt](https://github.com/ANZSoilData/def-au-domain/files/9875570/GLOSIS-physiochemical-properties.txt)

**Comment by dr-shorthair** [comment]
[GLOSIS-physiochemical-properties-with-codes.txt](https://github.com/ANZSoilData/def-au-domain/files/9875585/GLOSIS-physiochemical-properties-with-codes.txt)

**Comment by meganrwong** [comment]
GLOSIS is working on this, ENVO and AGRO also. Watch this space - we don't want to duplicate efforts.

**Comment by dr-shorthair** [comment]
Is there a link to their issue tracker?
