### ISSUE TITLE
Is 'qualification' an Observed Property?

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-domain#4]
In https://github.com/ANZSoilData/def-au-domain/issues/2#issuecomment-1208903631 @meganrwong asked: 

'qualification' has been added as Obsv Prop

Member - ‘field-texture-qualification'

@dr-shorthair not sure if 'Qualification' is an obsv prop

It may have a relationship to GRADE and its member field-texture-grade that may need to be expressed, but I’m not sure that is in scope of what we are doing here atm (may be skos:related of ‘field-texture-qualification' and ‘field-texture-grade')

**Comment by dr-shorthair** [comment]
I tend to agree. The observed-property is `field texture`. The coding (including qualification) is just one possible value-space. 
It is not an observed-property.

**Comment by meganrwong** [comment]
Yep, good. created https://anzsoil.org/def/au/property/horizon-classification

Re the text def for that - I started getting text from YB from 'as horizon notation is deduced from the profile description......' but do we want this here? It is kind of 'how to' method stuff. As a general comment, the YB does not tend to have super clear defs for obsv properites......I"ve not been putting them in yet. for now, just have skos:def 'Horizon Classification'

**Comment by dr-shorthair** [comment]
If the text at hand does not read like a definition, maybe put it in a `skos:note` instead, to save having to transcribe it later.

**Comment by meganrwong** [comment]
'grade' is not an obsv prop either but a value-space @dr-shorthair ? 
So we'd go:
sprop:texture>sprop:fieldtexture>spropfield-texture-mineral and sprop-field-texture-organic

**Comment by dr-shorthair** [comment]
Yes, the "Field texture grade" list (p162) is the primary value-space for Field-texture, which is combined with the coarse/fine, light/heavy and sapric/fibric qualifiers to get the full code for the field texture grade

**Comment by meganrwong** [comment]
what about sprop:grade-of-pedality then? We've put it under sprop:grade and sprop:structure 
'field-texture-grade' is a value-space and 'grade-of pedality' an observable property?? 
The lines are blurring for me.....

**Comment by meganrwong** [comment]
fixed - field-texture added, field-texture-grade removed. 
hierarchy sprop:texture>sprop:fieldtexture>spropfield-texture-mineral and sprop-field-texture-organic
