### ISSUE TITLE
Observable Properties with only one child?

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-domain#6]
In https://github.com/ANZSoilData/def-au-domain/issues/2#issuecomment-1208906322 @meganrwong noted: 

@dr-shorthair for record here is what has not been added as Observable Properties from ASLS soil profile chapter as there was only one instance. Could be added later as/if required. Let me know if you want any added now.

Have not add these higher level obsv prop – they have only 1 instance under

PERMEABILITY

DRAINAGE

MAGNETIC-ATTRIBUTES

EFFERVESCENCE of carbonates in fine earth

CEMENTATION

CONTINUITY

NATURE

FORM

CONDITION

FABRIC

DIAMETER - would go under linear extent

CONTRAST

?COLOUR – does not make sense to create given contexts is it found in (3 instances all with different use of colour)

Mottle-colour, colour-value and colour-stat

?DISTRIBUTION – only 1 instance

Course-fragment-distribution

(FIELD – not obsv prop) - does not make sense to add as upper level P161 – Field texture

**Comment by dr-shorthair** [comment]
I am inclined to add the top-level property for every case. 

I think the goal here is exactly to identify the top-level properties, with a view to deprecating the contextualized properties later and just leaving the non-contextualised properties in the vocabulary. We pretty much want to end up with none of th originals, and only the super-properties.

**Comment by meganrwong** [comment]
permeability, distribution, drainage added

**Comment by meganrwong** [comment]
'fabric' already there

**Comment by meganrwong** [comment]
all properties listed here have been added
