### ISSUE TITLE
Where are the members of 'Fabric'? 

### ISSUE THREAD

**Issue by dr-shorthair** [ANZSoilData/def-au-domain#7]
In https://github.com/ANZSoilData/def-au-domain/issues/2#issuecomment-1208907407 @meganrwong asked: 

@dr-shorthair Are we missing Obsv Prop members - under 'Fabric' - earthy, sandy rough and smooth? p181

**Comment by dr-shorthair** [comment]
AFAICT those 'members' are the value space - they are here: https://vocabs.ardc.edu.au/viewById/313 

The only 'observable property' is `sprop:fabric`

**Comment by meganrwong** [comment]
ok, thanks for clarifying for me! Closing
