### ISSUE TITLE
other colour patterns are not mottles?

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-domain#8]
![image](https://user-images.githubusercontent.com/49380601/184052457-16eeedd7-4143-4fbd-86d5-237d4011f74d.png)
![image](https://user-images.githubusercontent.com/49380601/184052512-d08b981c-2c78-48d0-a66d-8948e9ddf40b.png)

p160 YB
I think there are 4 ?feature-types here @dr-shorthair 
That is, I don't think Types X, Y and Z are all types of mottles?
So, for example, Y 'colour patterns due to mechanical mixing' can also have and abundance, size etc

**Comment by dr-shorthair** [comment]
Yes - the enumeration should be `Mottles or colour patterns type`
and I agree these are context (feature types) for the various properties.

**Comment by meganrwong** [comment]
so I'll remote sprop:mottle-type as an obsv prop
Then the question is how to encode the properties, something like this? getting long.....
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-abundance-abundance
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-abundance-size
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-abundance-contrast
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-abundance-colour
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-abundance-distinctness (which is distinctness-of-boundaries)

**Comment by dr-shorthair** [comment]
Wouldn't it be 
```
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-abundance
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-size
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-contrast
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-colour
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-distinctness
```

**Comment by meganrwong** [comment]
deeerrrrr, typo Megan, yes. Thanks Simon

addded
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-abundance
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-size
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-contrast
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-colour
https://anzsoil.org/def/au/property/mottles-and-colour-pattern-distinctness

moved def text to skos:notes since they were more a 'how to' than def of obsv prop
